def wake():
    wake_commands = [
        "hey qube",
        "hi qube",
        "hello qube",
        "okay qube",
        "alright qube",
        "qube",
        "qube are you there",
        "qube listen",
        "listen qube",
        "qube wake up",
        "wake up qube",
        "qube activate",
        "activate qube",
        "qube online",
        "qube come online",
        "qube i'm ready",
        "qube let's go",
        "qube start",
        "start qube",
        "qube I need you",
        "qube I need your help",
        "qube assist me",
        "qube respond",
        "qube report",
        "qube attention",
    ]
    return wake_commands